Rename use_tp to use_distributed (#1031)
Summary: use_tp was renamed to use_distributed in https://github.com/pytorch/torchchat/pull/873, but the PR missed generate.py, which caused "AttributeError: 'BuilderArgs' object has no attribute 'use_tp'" when running generate with --profile.