Patch triton (#820)
By patching runtime/jit.py with the contents of https://github.com/triton-lang/triton/pull/3564

Should fix intermittent
```
SyntaxError: unterminated string literal (detected at line 1)
```
for good

TODO: Delete `scripts/patch_trition.py` as well as changes to `install_requirements.sh` for good